# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here.
sys.path.insert(0, os.path.abspath('../src'))

# -- Project information -----------------------------------------------------

project = 'Confluence Content Parser'
copyright = '2025, Uladzislau Hubar'
author = 'Uladzislau Hubar'
release = '0.2.1'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.coverage',
    'sphinx.ext.githubpages',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',
    'logo_only': False,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#1a1a1a',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 5,
    'includehidden': True,
    'titles_only': False
}

# -- Options for autodoc ----------------------------------------------------

autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'undoc-members': True,
    'exclude-members': '__weakref__, model_config'
}

# -- Options for intersphinx extension --------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'pydantic': ('https://docs.pydantic.dev/latest/', None),
}

# -- Options for Napoleon extension -----------------------------------------

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Options for coverage extension -----------------------------------------

coverage_ignore_modules = []
coverage_ignore_functions = []
coverage_ignore_classes = []

# -- Options for autosummary extension --------------------------------------

autosummary_generate = True

# -- Custom configuration ---------------------------------------------------

# Add any additional configuration here
html_title = f"{project} v{release}"
html_short_title = project

# Custom CSS
html_css_files = [
    'custom.css',
]

# Custom JavaScript
html_js_files = []

# Logo (appears in sidebar and navigation)
html_logo = '_static/logo.svg'

# Favicon (appears in browser tab)
html_favicon = '_static/favicon.ico'

# Show "Edit on GitHub" links
html_context = {
    "display_github": True,
    "github_user": "Unificon",
    "github_repo": "confluence-content-parser",
    "github_version": "main",
    "conf_py_path": "/docs/",
}

# Link to source code
html_show_sourcelink = True

# Show copyright in footer
html_show_copyright = True

# Show "Created using Sphinx" in footer
html_show_sphinx = True

# Language for content autogenerated by Sphinx
language = 'en'

# The master toctree document
master_doc = 'index'

# Output file base name for HTML help builder
htmlhelp_basename = 'ConfluenceContentParserdoc'
